### ISSUE TITLE
Permission to list prompt on our website

### ISSUE THREAD

**Issue by qayyumabro** [editor-syntax/prompt-dataset#1]
Hi, Sorry this might be not the right place to ask but can you give us permission to include your prompt on our website?

We will add your website link (dofollow)on the prompt page.

Regards
Muhammad Qayyum

Prompts Database
[prmdb.com](http://prmdb.com/)

**Comment by editor-syntax** [comment]
> Hi, Sorry this might be not the right place to ask but can you give us permission to include your prompt on our website?
> 
> We will add your website link (dofollow)on the prompt page.
> 
> Regards Muhammad Qayyum
> 
> Prompts Database [prmdb.com](http://prmdb.com/)

Hello there, yes absolutely! No problem. 🙂

**Comment by qayyumabro** [comment]
Awesome, Thankyou.
